veranum/paginaweb/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    #INDEX Y LOGIN
    path('', views.index, name='index'),
    path('login_admin/', views.login_admin, name='login_admin'), #pagina de logueo
    path('cierre_sesion/', views.cierre_sesion, name='sesion_cierre'), #url de logout
    #PAGINA WEB
    path('hoteles/', views.hoteles, name='lista_hoteles'), #url hoteles
    path('ficha_hoteles/<int:id_hotel>/', views.ficha_hoteles, name='hotel_ficha'), #url de ficha hoteles con id de hotel para buscar
    path('tipo_habitaciones/', views.tipo_habitaciones, name='habitaciones_tipo'), #url de tipo de habitaciones
    path('servicios_adicionales/', views.servicios_adicionales, name='adicionales_servicios'), #url de servicios adicionales
    path('promociones/', views.promociones, name='lista_promociones'), #url promociones aprobadas
    #ADMIN
    #general
    path('portal_admin/', views.portal_admin, name='admin_portal'), #portal de administracion, diferenciado si es MKT o Gerencia
    path('portal_admin/promocion_preliminar/<str:codigo_promocion>/', views.preliminar, name='preliminar_promocion'), #url de promocion preliminar
    #marketing
    path('portal_admin/crear_promocion/', views.crear_promocion, name='promocion_crear'), #url para crear promocion
    path('portal_admin/editar_promocion/<str:codigo_promocion>/', views.editar_promocion, name='promocion_editar'), #url editar promocion
    path('portal_admin/eliminar_promocion/<str:codigo_promocion>/', views.eliminar_promocion, name='promocion_eliminar'), #url de eliminar promocion
    #gerencia
    path('portal_admin/promocion_preliminar/<str:codigo_promocion>/aprobar_rechazar', views.aprobar_rechazar, name='apruebo_o_rechazo'), #url de gerencia para aprobar o rechazar
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

veranum/veranum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginaweb.urls')),
]

veranum/paginaweb/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser

#MODELO PAGINA WEB VERANUM

#tabla Hotel
class Hotel (models.Model):
    id_hotel            = models.AutoField(primary_key=True) #autoincremental
    nombre_hotel        = models.CharField(max_length=50)
    direccion           = models.CharField(max_length=100) #nombre de la calle
    info_adicional_dir  = models.CharField(max_length=100, blank=True, null=True) #cualquier cosa adicional de la direccion
    comuna              = models.CharField(max_length=30) #solo son 2 hoteles, por tanto se ingresaran manualmente
    telefono            = models.CharField(max_length=10)
    correo_hotel        = models.EmailField(max_length=100)
    cant_habitaciones   = models.IntegerField() #cantidad de habitaciones, a definir
    desc_hotel          = models.TextField(blank=True, null=True) #usaremos lorem ipsum
    imagen_hotel        = models.CharField(max_length=100, blank=True, null=True) #para guardar la ruta de la imagen

    def __str__(self):
        return self.nombre_hotel


#tabla Servicio Adicional
class ServicioAdicional(models.Model):
    id_serv_adicional       = models.AutoField(primary_key=True) #autoincremental
    nombre_serv_adicional   = models.CharField(max_length=50)
    desc_serv_adicional     = models.TextField(blank=True, null=True) #lorem ipsum
    precio_serv_adicional   = models.IntegerField() #a definir si sera por noche o valor fijo adicional
    imagen_serv_adicional   = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.nombre_serv_adicional


#tabla Servicio por Hotel
class ServicioPorHotel(models.Model):
    id_servicio_hotel   = models.AutoField(primary_key=True) #autoincremental
    hotel               = models.ForeignKey(Hotel, on_delete=models.CASCADE) #FK de Hotel
    serv_adicional      = models.ForeignKey(ServicioAdicional, on_delete=models.CASCADE) #FK de Servicio Adicional

    class Meta:
        unique_together = ('hotel', 'serv_adicional')

    def __str__(self):
        return f'{self.hotel} - {self.serv_adicional}'


#tabla Tipo Habitacion
class TipoHabitacion(models.Model):
    id_tipo_habitacion      = models.AutoField(primary_key=True) #autoincremental
    nombre_tipo_habitacion  = models.CharField(max_length=20) #single, doble, triple, suite, backpacking, grupo
    cant_camas              = models.IntegerField() #definido por el tipo de hab
    bano_privado            = models.BooleanField()
    precio_noche            = models.IntegerField()
    desc_tipo_habitacion    = models.TextField(blank=True, null=True)
    imagen_tipo_habitacion  = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.nombre_tipo_habitacion


#tabla Habitacion
class Habitacion(models.Model):
    id_habitacion       = models.AutoField(primary_key=True) #autoincremental
    hotel               = models.ForeignKey(Hotel, on_delete=models.CASCADE) #FK de Hotel
    numero_habitacion   = models.IntegerField() #a definir el id de cada habitacion
    tipo_habitacion     = models.ForeignKey(TipoHabitacion, on_delete=models.CASCADE) #FK de Tipo Habitacion
    estado_habitacion   = models.BooleanField() #disponible o no disponible

    class Meta:
        unique_together = ('hotel', 'numero_habitacion')

    def __str__(self):
        return f'{self.hotel} - {self.numero_habitacion}'


#tabla Usuario
class Usuario(AbstractUser):
    rut             = models.CharField(unique=True, max_length=10) #rut completo
    
    ROLES_USUARIO   = [('M', 'Marketing'), ('G', 'Gerencia')] #arreglo con los roles de usuario definidos
    
    rol             = models.CharField(max_length=1, choices=ROLES_USUARIO, blank=True, null=True) #no hay default

    def __str__(self):
        return f'{self.username} - {self.rol}'


#tabla Promocion
class Promocion(models.Model):
    codigo_promocion    = models.CharField(primary_key=True, max_length=20) #id definido por el jefe de MKT, abreviacion del nombre
    hotel               = models.ForeignKey(Hotel, on_delete=models.CASCADE) #FK de Hotel
    tipo_habitacion     = models.ForeignKey(TipoHabitacion, on_delete=models.CASCADE) #FK de Tipo Habitacion
    nombre_promocion    = models.CharField(max_length=100)
    desc_promocion      = models.TextField(blank=True, null=True) #lorem ipsum
    fecha_inicio        = models.DateField() #fecha definida por jefe de MKT
    fecha_fin           = models.DateField() #fecha definida por jefe de MKT
    porc_descuento      = models.IntegerField() #porcentaje que define el jefe de MKT, sin decimales
    imagen_promocion    = models.ImageField(upload_to='assets/', blank=True, null=True) #para guardar las imagenes, luego cambiara a imagefield
    publicada_por       = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='promociones_publicadas', blank=True, null=True) #usuario de MKT que publica
    
    ESTADOS_PROMOCION   = [('P', 'Pendiente'), ('A', 'Aprobada'), ('R', 'Rechazada'), ('F', 'Finalizada')] #arreglo con estados de promocion
    
    estado_promocion    = models.CharField(max_length=1, choices=ESTADOS_PROMOCION, default='P') #estados de promocion definidos por el arreglo, por defecto Pendiente
    comentario          = models.TextField(blank=True, null=True) #comentario del gerente, en caso de querer dejar algo indicado
    fecha_revision      = models.DateTimeField(blank=True, null=True) #fecha de revision de la promocion por el usuario gerente
    revisada_por        = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='promociones_revisadas', blank=True, null=True) #FK de Usuario, en blanco hasta que el gerente la apruebe o rechace
    
    #metodo para guardar datos automaticos en la tabla promocion
    def save(self, *args, **kwargs):
        update_fields = set()
        #si el estado de la promocion es Aprobada o Rechazada, se guarda la fecha de revision
        if self.estado_promocion in ['A', 'R'] and not self.fecha_revision:
            self.fecha_revision = timezone.now().date()
            update_fields.add('fecha_revision')
        #guarda los cambios
        super().save(*args, **kwargs)
        #verifica si se actualizo algun campo que requiera un segundo guardado
        if update_fields:
            super(Promocion, self).save(update_fields=update_fields)

    def __str__(self):
        return self.codigo_promocion

veranum/paginaweb/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Hotel, ServicioAdicional, TipoHabitacion, Habitacion, Promocion, ServicioPorHotel
from django.http import JsonResponse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import PromocionForm, GerenciaPromocionForm


#INDEX Y LOGIN
#pagina index
def index(request):
    return render(request, 'paginaweb/index.html')

#login
def login_admin(request):
    if request.method == 'POST':
        username = request.POST.get('usuario')
        password = request.POST.get('clave')
        #autentificar usando username y password
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return JsonResponse({'success': True, 'message': 'Ingreso exitoso.', 'rol': user.rol})
        else:
            return JsonResponse({'success': False, 'message': 'Credenciales incorrectas.'})
    return render(request, 'paginaweb/login.html')

#redireccionar al login si usuario no esta logueado
def login_required(view_func):
    def wrapper(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse('login_admin'))
        return view_func(request, *args, **kwargs)
    return wrapper

#logout
@login_required
def cierre_sesion(request):
    logout(request)
    return redirect('index')


#PAGINA WEB
#hoteles
def hoteles(request):
    hoteles = Hotel.objects.all()
    return render(request, 'paginaweb/hoteles.html', {'hoteles': hoteles})

#ficha hoteles
def ficha_hoteles(request, id_hotel):
    hotel = get_object_or_404(Hotel, id_hotel=id_hotel)
    habitaciones = Habitacion.objects.filter(hotel=hotel)
    servicios = ServicioPorHotel.objects.filter(hotel=hotel)
    return render(request, 'paginaweb/ficha_hotel.html', {'hotel': hotel, 'habitaciones': habitaciones, 'servicios': servicios})

#tipo habitaciones
def tipo_habitaciones(request):
    tipo_habitaciones = TipoHabitacion.objects.all()
    return render(request, 'paginaweb/tipo_habitaciones.html', {'tipo_habitaciones': tipo_habitaciones})

#pagina de servicios adicionales
def servicios_adicionales(request):
    servicios_adicionales = ServicioAdicional.objects.all()
    return render(request, 'paginaweb/servicios_adicionales.html', {'servicios_adicionales': servicios_adicionales})

#promociones aprobadas
def promociones(request):
    promociones = Promocion.objects.filter(estado_promocion='A')
    return render(request, 'paginaweb/promociones.html', {'promociones': promociones})


#ADMINISTRACION GENERAL
#portal admin
@login_required
def portal_admin(request):
    promociones = Promocion.objects.all()
    if request.user.rol == 'G':
        promociones = promociones.filter(estado_promocion='P')
    return render(request, 'paginaweb/portal_admin.html', {'promociones': promociones})

#promocion preliminar para revision
@login_required
def preliminar(request, codigo_promocion):
    promocion = get_object_or_404(Promocion, codigo_promocion=codigo_promocion)
    form = GerenciaPromocionForm(instance=promocion)
    return render(request, 'paginaweb/promocion_preliminar.html', {'promocion': promocion, 'form': form})


#MARKETING
#crear promocion
@login_required
def crear_promocion(request):
    if request.method == 'POST':
        form = PromocionForm(request.POST, request.FILES)
        if form.is_valid():
            promocion = form.save(commit=False)
            promocion.publicada_por = request.user
            if 'imagen_promocion' in request.FILES:
                imagen_promocion = request.FILES['imagen_promocion']
                direccion_guardado = FileSystemStorage(location = 'paginaweb/static/assets')
                nombre_archivo = direccion_guardado.save(imagen_promocion.name, imagen_promocion)
                imagen_promocion_URL = 'assets/' + nombre_archivo
                promocion.imagen_promocion = imagen_promocion_URL
            promocion.save()
            return JsonResponse({'success': True, 'message': 'Promoción creada exitosamente.'})
        else:
            errors = form.errors.as_json()
            return JsonResponse({'success': False, 'message': 'Error en la validación del formulario.', 'errors': errors})
    else:
        form = PromocionForm()
    return render(request, 'paginaweb/crear_promocion.html', {'form': form})

#editar promocion
@login_required
def editar_promocion(request, codigo_promocion):
    promocion = get_object_or_404(Promocion, codigo_promocion=codigo_promocion)
    if request.method == 'POST':
        form = PromocionForm(request.POST, request.FILES, instance=promocion)
        if form.is_valid():
            promocion = form.save(commit=False)
            promocion.publicada_por = request.user
            if 'imagen_promocion' in request.FILES:
                imagen_promocion = request.FILES['imagen_promocion']
                direccion_guardado = FileSystemStorage(location='paginaweb/static/assets')
                nombre_archivo = direccion_guardado.save(imagen_promocion.name, imagen_promocion)
                imagen_promocion_URL = 'assets/' + nombre_archivo
                promocion.imagen_promocion = imagen_promocion_URL
            promocion.save()
            return JsonResponse({'success': True, 'message': 'Promoción actualizada exitosamente.'})
        else:
            errors = form.errors.as_json()
            return JsonResponse({'success': False, 'message': 'Error en la validación del formulario.', 'errors': errors})
    else:
        form = PromocionForm(instance=promocion)
    return render(request, 'paginaweb/editar_promocion.html', {'form': form, 'promocion': promocion})

#eliminar promocion
@login_required
def eliminar_promocion(request, codigo_promocion):
    try:
        promocion = Promocion.objects.get(codigo_promocion=codigo_promocion)
        promocion.delete()
        return JsonResponse({'success': True})
    except Promocion.DoesNotExist:
        return JsonResponse({'success': False, 'message': 'Promocion no encontrada.'})
    except Exception as e:
        return JsonResponse({'success': False, 'error': str(e)})


#GERENCIA
#aprobar o rechazar promocion
@login_required
def aprobar_rechazar(request, codigo_promocion):
    promocion = get_object_or_404(Promocion, codigo_promocion=codigo_promocion)
    if request.method == 'POST':
        form = GerenciaPromocionForm(request.POST, instance=promocion)
        if form.is_valid():
            #guardar el comentario y la revision por el usuario de gerencia
            promocion.comentario = form.cleaned_data['comentario']
            promocion.revisada_por = request.user
            #validacion si aprueba o rechaza
            if 'aprobar' in request.POST:
                promocion.estado_promocion = 'A'
            elif 'rechazar' in request.POST:
                promocion.estado_promocion = 'R'
            promocion.save()
            return JsonResponse({'success': True, 'message': 'Estado de promoción actualizado correctamente.'})
        else:
            errors = form.errors.as_json()
            return JsonResponse({'success': False, 'message': 'Error en la validación del formulario.', 'errors': errors})

veranum/paginaweb/templates/paginaweb/crear_promocion.html
{% extends 'base.html' %}

{% block title %}
    Crear Promoción
{% endblock %}

{% block content %}
    {% load static %}
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Crear Promoción</h2>
                <form id="form_crearPromocion" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary" id="btn_crearPromocion">Guardar</button>
                    <a type="button" class="btn btn-warning" href="{% url 'admin_portal' %}">Volver</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% load static %}
    <script src="{% static 'js/crear_promocion.js' %}"></script>
{% endblock %}

veranum/paginaweb/templates/paginaweb/editar_promocion.html
{% extends 'base.html' %}

{% block title %}
    Editar Promoción
{% endblock %}

{% block content %}
    {% load static %}
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <h2>Editar Promoción</h2>
                <form id="form_editarPromocion" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="hotel">Hotel</label>
                        {{ form.hotel }}
                    </div>
                    <div class="form-group">
                        <label for="tipo_habitacion">Habitación</label>
                        {{ form.tipo_habitacion }}
                    </div>
                    <div class="form-group">
                        <label for="codigo_promocion">Código</label>
                        {{ form.codigo_promocion }}
                    </div>
                    <div class="form-group">
                        <label for="nombre_promocion">Nombre de la promoción</label>
                        {{ form.nombre_promocion }}
                    </div>
                    <div class="form-group">
                        <label for="fecha_inicio">Fecha de inicio</label>
                        <input type="date" name="fecha_inicio" value="{{ form.instance.fecha_inicio|date:"Y-m-d" }}" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="fecha_fin">Fecha de finalización</label>
                        <input type="date" name="fecha_fin" value="{{ form.instance.fecha_fin|date:"Y-m-d" }}" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="porc_descuento">Porcentaje de descuento</label>
                        {{ form.porc_descuento }}
                    </div>
                    <div class="form-group">
                        <label for="desc_promocion">Descripción de la promoción</label>
                        {{ form.desc_promocion }}
                    </div>
                    <div class="form-group">
                        <label for="imagen_promocion">Carga la imagen de la promoción</label>
                        {{ form.imagen_promocion }}
                    </div>
                    <div class="mt-3">
                        <button type="submit" class="btn btn-primary" id="btn_editarPromocion">Guardar</button>
                        <a type="button" class="btn btn-warning" href="{% url 'admin_portal' %}">Volver</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    {% load static %}
    <script src="{% static 'js/editar_promocion.js' %}"></script>
{% endblock %}

veranum/paginaweb/templates/paginaweb/ficha_hotel.html
{% extends 'base.html' %}

{% block title %}
    Hoteles
{% endblock %}

{% block content %}
    {% load static %}
    <div class="card mb-3 mt-3 mx-3">
        <h1 class="mt-1">{{ hotel.nombre_hotel }}</h1>
        <img src="{% static hotel.imagen_hotel %}" class="card-img-top mt-1" alt="Imagen de {{ hotel.nombre_hotel }}">
        <div class="card-body">
            <h5 class="card-title">Datos del hotel</h5>
            <p class="card-text"><strong>Cantidad de habitaciones:</strong> {{ hotel.cant_habitaciones }}</p>
            <p class="card-text"><strong>Dirección:</strong> {{ hotel.direccion }}, {{ hotel.comuna }}</p>
            <p class="card-text"><strong>Teléfono:</strong> {{ hotel.telefono }}</p>
            <p class="card-text"><strong>Correo:</strong> {{ hotel.correo_hotel }}</p>
        </div>
    </div>

    <div class="container mt-5">
        <h2>Servicios Disponibles por Hotel</h2>
        <div class="row">
            {% for servicio in servicios %}
                <div class="col-md-4">
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ servicio.serv_adicional.nombre_serv_adicional }}</h5>
                            <p class="card-text"><strong>Precio adicional:</strong> ${{ servicio.serv_adicional.precio_serv_adicional }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="container mt-5">
        <h2>Habitaciones</h2>
        <div class="row">
            {% for habitacion in habitaciones %}
                <div class="col-md-4">
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">Habitación {{ habitacion.numero_habitacion }}</h5>
                            <p class="card-text">Tipo de habitación: {{ habitacion.tipo_habitacion.nombre_tipo_habitacion }}</p>
                            <p class="card-text"><strong>Camas:</strong> {{ habitacion.tipo_habitacion.cant_camas }}</p>
                            <p class="card-text"><strong>Baño privado:</strong> {% if habitacion.tipo_habitacion.bano_privado %}Sí{% else %}No{% endif %}</p>
                            <p class="card-text"><strong>Precio por noche:</strong> ${{ habitacion.tipo_habitacion.precio_noche }}</p>
                            <p class="card-text"><strong>Estado:</strong> {% if habitacion.estado_habitacion %}Disponible{% else %}No disponible{% endif %}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div>
        <a type="button" class="btn btn-warning mx-5" href="{% url 'lista_hoteles' %}">Volver a Hoteles</a>
    </div>
{% endblock %}

{% block footer %}
    {% load static %}
    <script src=""></script>
{% endblock %}

veranum/paginaweb/templates/paginaweb/hoteles.html
{% extends 'base.html' %}

{% block title %}
    Hoteles
{% endblock %}

{% block content %}
    {% load static %}
    {% for hotel in hoteles %}
        <div class="card mb-3 mt-3 mx-3">
            <img src="{% static hotel.imagen_hotel %}" class="card-img-top imagen-hotel" alt="Imagen de {{ hotel.nombre_hotel }}">
            <div class="card-body">
                <h5 class="card-title">{{ hotel.nombre_hotel }}</h5>
                <p class="card-text">{{ hotel.desc_hotel }}</p>
                <p class="card-text"><small class="text-body-secondary">Dirección: {{ hotel.direccion }}, {{ hotel.comuna }}</small></p>
                <a type="button" class="btn btn-warning" href="{% url 'hotel_ficha' hotel.id_hotel %}">Ir al Hotel</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block footer %}
    {% load static %}
    <script src=""></script>
{% endblock %}

veranum/paginaweb/templates/paginaweb/index.html
{% extends 'base.html' %}

{% block title %}
    Veranum
{% endblock %}

{% block content %}
    {% load static %}
    <main>
        <section class="main-content image-sections">
            <section class="options image-section">
                <h2>Opciones</h2>
                <ul>
                    <li>
                        <a href="">
                            <img src="https://imgcy.trivago.com//hardcodedimages/homepage-landing/usp/SearchDesktop.svg" alt="Hoteles">
                            Hoteles
                        </a>
                        <p>Busca rápido<br>Busca entre cualquiera de nuestros dos hoteles.</p>
                    </li>
                    <li>
                        <a href="">
                            <img src="https://imgcy.trivago.com//hardcodedimages/homepage-landing/usp/CompareDesktop.svg" alt="Habitaciones">
                            Habitaciones
                        </a>
                        <p>Revisa<br>Revisa todas nuestras habitaciones a los mejores precios.</p>
                    </li>
                    <li>
                        <a href="">
                            <img src="https://imgcy.trivago.com//hardcodedimages/homepage-landing/usp/SaveDesktop.svg" alt="Servicios Adicionales">
                            Servicios Adicionales
                        </a>
                        <p>Ahorra a lo grande<br>Descubre increíbles ofertas en nuestra página web.</p>
                    </li>
                </ul>
            </section>
            <section class="image-sections">
                <div class="image-section" id="hoteles">
                    <img src="{% static 'assets/1.jpg' %}" alt="Hoteles">
                    <a href="{% url 'lista_hoteles' %}"><button>Hoteles</button></a>
                </div>
                <div class="image-section" id="habitaciones">
                    <img src="{% static 'assets/3.jpg' %}" alt="Habitaciones">
                    <a href="{% url 'habitaciones_tipo' %}"><button>Habitaciones</button></a>
                </div>
                <div class="image-section" id="servicios">
                    <img src="{% static 'assets/2.jpg' %}" alt="Servicios Adicionales">
                    <a href="{% url 'adicionales_servicios' %}"><button>Servicios Adicionales</button></a>
                </div>
                <div class="image-section" id="promociones">
                    <img src="{% static 'assets/3.jpg' %}" alt="Promociones">
                    <a href="{% url 'lista_promociones' %}"><button>Promociones</button></a>
                </div>
            </section>
        </section>
    </main>
{% endblock %}

{% block footer %}
    {% load static %}
    <script src=""></script>
{% endblock %}

veranum/paginaweb/templates/paginaweb/login.html
{% extends 'base.html' %}

{% block title %}
    Veranum
{% endblock %}

{% block content %}
    {% load static %}
    <main>
        <section class="">
            <div class="container">
                <div class="row justify-content-center mt-4 mb-4">
                    <div class="col-md-6">
                        <div class="card shadow-sm rounded">
                            <div class="card-body">
                                <h1 class="text-center">Login</h1>
                                <form id="form_login" method="POST" action="{% url 'login_admin' %}">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label for="txt_usuario" class="form-label">Usuario</label>
                                        <input type="text" class="form-control" id="txt_usuario" name="usuario" required />
                                    </div>
                                    <div class="mb-3">
                                        <label for="txt_clave" class="form-label">Contraseña</label>
                                        <input type="password" class="form-control" id="txt_clave" name="clave" required />
                                    </div>
                                    <button type="submit" class="btn btn-warning" id="btn_login">Iniciar sesión</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

{% block footer %}
    {% load static %}
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}

veranum/paginaweb/templates/paginaweb/promocion_preliminar.html
{% extends 'base.html' %}

{% block title %}
    Detalle de Promoción
{% endblock %}

{% block content %}
    {% load static %}
    <div class="container mt-5 mb-5">
        <h1 class="text-center mb-5">Previsualización de la Promoción</h1>
        <h2 class="text-center">{{ promocion.nombre_promocion }}</h2>
        <div class="text-center mt-4">
            {% if promocion.imagen_promocion %}
                <img src="{% static promocion.imagen_promocion %}" alt="Imagen de la promoción" class="img-fluid" style="max-width: 1000px; height: auto;">
            {% else %}
                <img src="{% static 'assets/promocion_generica.jpg' %}" alt="Imagen por defecto" class="img-fluid" style="max-width: 1000px; height: auto;">
            {% endif %}
        </div>
        <div class="mt-4">
            <div class="text-center mt-4 mb-4 p-3 rounded border">
                <p><strong>{{ promocion.porc_descuento }}% de descuento</strong> en el <strong>{{ promocion.hotel.nombre_hotel }}</strong> en todas las habitaciones <strong>{{ promocion.tipo_habitacion.nombre_tipo_habitacion }}</strong></p>
                <p><strong>Duración:</strong> Desde el <strong>{{ promocion.fecha_inicio }}</strong> al <strong>{{ promocion.fecha_fin }}</strong></p>
                <p>{{ promocion.desc_promocion }}</p>
            </div>
        </div>
        {% if user.rol == 'M' %}
            <div class="mt-4 mb-4 p-3 rounded border">
                <h4>Detalles Administrativos</h4>
                <p><strong>Publicada por:</strong> {{ promocion.publicada_por.username }}</p>
                <p><strong>Estado de la promoción:</strong> {{ promocion.get_estado_promocion_display }}</p>
                <p><strong>Comentario:</strong> {{ promocion.comentario }}</p>
                <p><strong>Fecha de revisión:</strong> {{ promocion.fecha_revision }}</p>
                <p><strong>Revisada por:</strong> {{ promocion.revisada_por.username }}</p>
            </div>
        {% elif user.rol == 'G' %}
            <form class="form_aprobarRechazar" method="post" action="{% url 'apruebo_o_rechazo' promocion.codigo_promocion %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" name="aprobar" class="btn btn-success btn_aprobar">Aprobar</button>
                <button type="submit" name="rechazar" class="btn btn-danger btn_rechazar">Rechazar</button>
            </form>
        {% endif %}
        <a type="button" class="btn btn-warning mt-3" href="{% url 'admin_portal' %}">Volver</a>
    </div>
{% endblock %}

{% block footer %}
    {% load static %}
    <script src="{% static 'js/aprobar_rechazar.js' %}"></script>
{% endblock %}